config/routes.rb
Rails.application.routes.draw do


  # get 'static/index'
  get 'dashboards/index'

  get 'one_sheets/write_email' => 'one_sheets#write_email'
  post 'one_sheets/send_email' => 'one_sheets#send_email'
  get 'email_sent' => 'static#email_sent'

  root 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/one_sheets_controller.rb
class OneSheetsController < ApplicationController

  def write_email
  end

  def send_email
    OneSheetMailer.send_onesheet(params[:address]).deliver_now
    # redirect_back(fallback_location: root_path)
    redirect_to email_sent_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @skip_header = true
    @skip_footer = true
  end

  def email_sent
    @skip_header = true
    @skip_footer = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/one_sheets_helper.rb
module OneSheetsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dashboards/index.html.erb
<div class='jumbotron jumbotron-fluid jumbo-parallax text-white'>
  <center><%= image_tag('Asset_6.png', class: 'main-logo') %></center>
  <p class='lead'>We're backend experts with an eye on speed</p>
  <div class='jumbo-p'>
    <p>We make apps that are, above all, readable—so they're easy to maintain
      and update long after we're off the project.</p>
    <p>Our extensive network of freelance designers, photographers, producers and
      writers ensure your project gets exactly what it needs without the budget
      bloat of traditional agencies.</p>
  </div>
</div>

<div class='container-fluid'>

  <div class='row title'>
    <div class='col'>
      <center><h1>SERVICES</h1></center>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-4'>
      <center><%= image_tag('007-webpage.png', class: 'serv-icon') %>
      <h3 class='serv-head'>MOBILE-FIRST WEB APPS</h3>
      <p>We use the fastest frameworks with the cleanest logic.</p></center>
    </div>
    <div class='col-sm-4'>
      <center><%= image_tag('032-wifi-signal.png', class: 'serv-icon') %>
        <h3 class='serv-head'>MULTIPLE PLATFORMS</h3>
        <p>We pride ourselves on adding new apps to existing systems—without
          interrupting workflows.</p></center>
    </div>
    <div class='col-sm-4'>
      <center><%= image_tag('033-user.png', class: 'serv-icon') %>
        <h3 class='serv-head'>EMPATHETIC DESIGN</h3>
        <p>These apps are for you, so we are responsive, nimble and ready
          to keep you in the center of the process.</p></center>
    </div>
  </div>

  <div class='row bg-gray pad-top'>
    <div class='col-sm-6'>
      <center><h1>THE PHILOSOPHY</h1></center>
    </div>
    <div class='col-sm-6 mx-auto'>
      <center><h1>THE WORK</h1></center>
    </div>
  </div>
  <div class='row bg-gray pad-top'>
    <div class='col-sm-5 mx-auto'>
      <p>We build web apps. Think of it as any website that needs to get
        information from a database, or one that needs to send automated emails.</p>
      <p>But it's more than that. We build APIs too, which give any website the
        ability to interface with a database.</p>
      <p>All our projects are completed with the understanding that you want the
        best product possible. Which includes writing code that is clean,
        maintainable and easy for future collaborators to update.</p>
      <p>All our designs take the back end of the app into account. We're
        builders, not designers—but, thanks to our extensive experience as
        freelancers, we have access to the top talent in whatever a
        medium-to-large company could need.</p>
    </div>
    <div class='col-sm-5 mx-auto'>
      <p>PLUS EQUALS has extensive experience in Ruby on Rails apps,
        particularly in building APIs and integrating new apps into old systems.</p>
      <p>Jim has been building open-source software—his favorite so far is the
        API of Samuel Johnson's dictionary from 1755 (he used to be an editor,
        so he has strong opinions about dictionaries). You can see the code
        <%= link_to 'here', 'https://github.com/Publicover/samuel_johnson_api' %>.
        Raymahl has been working on a startup that uses machine learning to
        remove human error from the hiring process in any industry over at
        <%= link_to 'applyable', 'https://www.applyable.io/' %>.</p>
      <p>You can download a one pager about us
        <%= link_to 'here', '/test_file.txt' %>.</p>
    </div>
  </div>




  <div class='row pad-top'>
    <h1 class='mx-auto'>THE TEAM</h1>
  </div>
  <div class='row' id='card-holder'>
    <div class='col-sm-3 mx-auto d-flex'>
      <div class='card'>
        <%= image_tag("boys_porch.jpg", alt: "Jim and the boys.",
                                        size: '150x150',
                                        class: 'img-fluid d-block card-img-top') %>
        <div class='card-body'>
          <h5 class='card-title'>JIM PUBLICOVER</h5>
          <p class='card-text'>Ruby on Rails, <br />Copy</p>
        </div>
      </div>
    </div>
    <div class='col-sm-3 mx-auto d-flex'>
      <div class='card'>
        <%= image_tag('raymahl.jpg',
                       alt: 'Raymahl',
                       size: '150x150',
                       class: 'img-fluid d-block card-img-top') %>
        <div class='card-body'>
          <h5 class='card-title'>Raymahl Sutton</h5>
          <p class='card-text'>Ruby on Rails,<br />Accounts</p>
        </div>
      </div>
    </div>
    <div class='col-sm-3 mx-auto d-flex'>
      <div class='card'>
        <%= image_tag('customer2.jpg',
                      alt: 'You, of course',
                      size: '150x150',
                      class: 'img-fluid d-block card-img-top') %>
        <div class='card-body'>
          <h5 class='card-title'>Our professional network</h5>
          <p class='card-text'>The Triad's top talent</p>
        </div>
      </div>
    </div>

    </div>

  <div class='row bg-gray pad-top'>
    <div class='col'>
      <center>
        <h1>THE IDEAL WORKFLOW</h1>
      </center>
    </div>
  </div>

  <div class='row bg-gray pad-top'>
    <div class='col-sm-5 mx-auto'>
      <p><span class='para-head'>You</span> have an idea of what you want to accomplish.</p>
      <p>You're looking for agency-quality work without the sluggish timelines,
        muddled communications and bloated budgets that come with an agency.</p>
      <p>You don't have a six-figure budget and you don't want to hold anyone's hand.</p>
    </div>
    <div class='col-sm-5 mx-auto'>
      <p><span class='para-head'>WE</span> are tired of business getting in the
        way of work.</p>
      <p>We are passionate coders who love what we do.</p>
      <p>We are highly adept at explaining technical information to non-technical
        stakeholders—but we know that you probably don't care about small details.</p>
    </div>
  </div>
  <div class='row bg-gray pad-top'>
    <div class='col-sm-12 mx-auto above-all'>
      <p><span class='para-head'>ABOVE ALL,</span> our code is clean and
        elegant, which means that whoever maintains the app after we build it
        won't encounter any mysterious or magical code blocks.</p>
    </div>
  </div>

  <div class='row pad-top'>
    <div class='col'>
      <center><h1>THE CLIENTS</h1></center>
    </div>
  </div>

  <div class='row pad-top'>

    <div class='col mx-auto client_mla mla-img'>
      <div class='hov-hidden'>
        <center>
          <h4>Marine Leadership Alliance</h4>
          <p>The MLA needed a web app that would allow members to make reservations
            for their annual conference. And the workflow had to integrate with
            the administrator's MS Office from 2007.</p>
        </center>
      </div>
    </div>

    <div class='col mx-auto client_dash dash-img'>
      <div class='hov-hidden'>
        <center>
          <h4>dash creative</h4>
          <p>dash creative was engaged to build an app for startup incubators that
            could help students and teachers both track the curriculae. Reminder
            emails, deadlines, a slick reactive interface were the main features.</p>
        </center>
      </div>
    </div>

    <div class='col mx-auto client_johnson johnson-img'>
      <div class='hov-hidden'>
        <center>
          <h4>The Johnson Society of London</h4>
          <p>Jim spent more than a decade as writer and editor, so he has some strong
            opinions about dictionaries. He created an API (a database interface)
            for Samuel Johnson's famous dictionary from 1755 as an open-source
            love letter to word nerds everywhere.</p>
        </center>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlusEquals</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= render 'partials/header' unless @skip_header %>
    <%= yield %>
    <%= render 'partials/footer' unless @skip_footer %>
  </body>
</html>

app/views/one_sheets/_write_email.html.erb
<h4>Get our one-sheet by email by entering your address below.</h4>

<%= form_tag one_sheets_send_email_path do %>
  <%= email_field_tag :address, nil, placeholder: "Email address" %>
  <%= submit_tag "SEND ME AN EMAIL"%>
<% end %>

app/views/one_sheets/write_email.html.erb
Get our one-sheet by email by entering your address below.

<%= form_tag one_sheets_send_email do %>
  <%= email_field_tag :address, nil, placeholder: "Email address" %>
  <%= submit_tag "SEND ME AN EMAIL"%>
<% end %>

app/views/partials/_footer.html.erb
<footer class='page-footer white'>
  <div class='container'>
    <div class='row center'>
      <div class='col f-block'>
        <h3>Contact</h3>
        Send us an email at <%= mail_to 'accounts@plusequals.io' %>.
      </div>
      <div class='col f-block'>
        <h3>Jim's links</h3>
        See Jim's <%= link_to 'portfolio', 'https://publicoverpress.herokuapp.com/'%>
        <br />or check him out on <%= link_to 'LinkedIn', "#{ENV['MY_LI']}" %>.
      </div>
      <div class='col f-block'>
        <h3>Raymahl's links</h3>
        See Raymahl's <%= link_to 'LinkedIn profile', "#{ENV['RAYMAHL_LI']}" %>.
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class='navbar navbar-expand-sm navbar-dark sticky-top'>

  <div>

    <%= image_tag('Asset_4.png',
                   size: '75x75',
                   class: 'navbar-brand mb-0') %>
  </div>

  <button type="button" class="btn-sm navbar-toggler navbar-toggler-right"
          data-toggle="collapse" data-target="#myNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class='collapse navbar-collapse' id='myNavbar'>
    <ul class='navbar-nav ml-auto text-nowrap'>
      <li class='nav-item nav-link <%= 'active' if current_page?(root_path) %>'>
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>

</nav>